[package]
name = "download-manager"
version = "0.1.0"
edition.workspace = true

[dependencies]
async-broadcast.workspace = true
async-channel.workspace = true
async-fs.workspace = true
async-io.workspace = true
blocking.workspace = true
flate2.workspace = true
futures-core.workspace = true
futures-lite.workspace = true
futures-util = { workspace = true, features = ["io"] }
http.workspace = true
http-client.workspace = true
thiserror.workspace = true
derive_builder.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tokio-util = { workspace = true, features = ["rt"] }
uuid.workspace = true
url.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
