[package]
name = "download-manager"
version = "0.1.0"
edition.workspace = true

[dependencies]
reqwest.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true, features = ["sync"] }
tokio-util = { workspace = true, features = ["full"] }
futures-core.workspace = true
futures-util.workspace = true
thiserror.workspace = true
derive_builder.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
